name: Deploy to Azure (main)

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps & test
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m pytest -q

      - name: Zip artifact
        run: |
          zip -r app.zip . -x ".git/*" ".github/*" ".venv/*" "tests/*"

      # Direkter ZIP-Deploy zur Kudu-API mit den Zugangsdaten aus dem Publish Profile
      - name: Deploy via Kudu ZIP API (publish profile)
        shell: bash
        env:
          PUBLISH_PROFILE: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
        run: |
          python - <<'PY'
          import os, sys, xml.etree.ElementTree as ET, subprocess
          xml = os.environ['PUBLISH_PROFILE']
          root = ET.fromstring(xml)
          prof = None
          for p in root.findall('.//publishProfile'):
              method = p.attrib.get('publishMethod','').lower()
              if method in ('msdeploy','zipdeploy','webdeploy'):
                  prof = p; break
          if not prof:
              print("No MSDeploy/ZipDeploy profile found", file=sys.stderr)
              sys.exit(1)

          publishUrl = prof.attrib['publishUrl']   # <app>.scm.spaincentral-01.azurewebsites.net:443
          host = publishUrl.split(':')[0]
          user = prof.attrib['userName']
          pwd  = prof.attrib['userPWD']
          url  = f"https://{host}/api/zipdeploy"

          print(f"Deploying to {url}")
          r = subprocess.run(['curl','-sS','-u', f'{user}:{pwd}', '-X','POST', url, '--data-binary','@app.zip'])
          sys.exit(r.returncode)
          PY